---
- include: virtualenv.yml

- name: Enable the pagespeed module
  apache2_module: state=present name=pagespeed

- name: Print shared_filesystem_type
  debug:
    var: shared_filesystem_type

- name: Install Upstart script
  template:
    src: upstart/create_pagespeed_cache_folder.conf.j2
    dest: /etc/init/apache-pagespeed-cache.conf
    mode: 0644
    owner: root
    group: root
  when: ansible_lsb.major_release|int < 16

- block:
  - name: Install create_pagespeed_cache_folder service (systemd)
    template:
      src: systemd/create_pagespeed_cache_folder.service.j2
      dest: /etc/systemd/system/create_pagespeed_cache_folder.service
      mode: 0644
      owner: root
      group: root

  - name: Enable the create_pagespeed_cache_folder service (systemd)
    service:
      name: create_pagespeed_cache_folder
      enabled: yes

  - name: Start the create_pagespeed_cache_folder service (systemd)
    service:
      name: create_pagespeed_cache_folder
      state: started
    ignore_errors: true
  when: ansible_lsb.major_release|int >= 16

- name: Copy the pagespeed-upstart.sh bash script
  template:
    src: "pagespeed-upstart.sh.j2"
    dest: "{{ scripts_dir }}/apache-pagespeed/pagespeed-upstart.sh"
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
